#!/bin/sh -ex

cd $(dirname $(readlink -f $0))

container="lmp-dr-devshell"

docker build -t ${container} -f Dockerfile.devshell ./

docker run --rm -it \
	-v `pwd`:`pwd` \
	-w `pwd` \
	${container} /bin/bash
